-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module GitHub.Object.SponsorsListing exposing (..)

import GitHub.InputObject
import GitHub.Interface
import GitHub.Object
import GitHub.Scalar
import GitHub.ScalarCodecs
import GitHub.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The full description of the listing.
-}
fullDescription : SelectionSet String GitHub.Object.SponsorsListing
fullDescription =
    Object.selectionForField "String" "fullDescription" [] Decode.string


id : SelectionSet GitHub.ScalarCodecs.Id GitHub.Object.SponsorsListing
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (GitHub.ScalarCodecs.codecs |> GitHub.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The short description of the listing.
-}
shortDescription : SelectionSet String GitHub.Object.SponsorsListing
shortDescription =
    Object.selectionForField "String" "shortDescription" [] Decode.string


{-| The short name of the listing.
-}
slug : SelectionSet String GitHub.Object.SponsorsListing
slug =
    Object.selectionForField "String" "slug" [] Decode.string
